language: go
go:
- 1.x
script:
# confirm the generator script is in sync with the assembly file
- block=$(mktemp)
- go run make_block.go -out ${block}
- cmp block_amd64.s ${block}
# run tests
- go test -v
# ensure we can build the testvector generator
- make -C testdata testvectors
- tv=$(mktemp)
- ./testdata/testvectors -s 42 >${tv}
- go test -v -testvectors ${tv}